# Generated by Django 3.0.8 on 2021-11-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=300)),
                ('number_searches', models.IntegerField()),
                ('number_results', models.IntegerField()),
            ],
        ),
    ]
